[versions]
agp = "8.3.1"
playServicesWearable = "18.0.0"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

